specify correct build context

diff --git a/.github/workflows/batch1.yaml b/.github/workflows/batch1.yaml
--- a/.github/workflows/batch1.yaml
+++ b/.github/workflows/batch1.yaml
@@ -37,6 +37,13 @@ jobs:
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v2
 
+    - name: Verify Dockerfile exists
+      run: |
+        if [ ! -f codegen/Dockerfile ]; then
+          echo "Dockerfile not found!"
+          exit 1
+        fi
+
     - name: Build, tag, and push docker image to Amazon ECR
       env:
         AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
