modify dependabot to access the necessary resources

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -164,25 +164,24 @@ jobs:
     - uses: actions/setup-go@v4
       with:
         go-version: '1.20'
-    - name: Get Security Alerts
+    - name: Get Dependabot alerts
       env:
-        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
-        response=$(curl -s \
-          -H "Accept: application/vnd.github.v4+json" \
-          -H "Authorization: Bearer $GH_TOKEN" \
-          "https://api.github.com/repos/${{ github.repository }}/vulnerability-alerts")
+        response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
+          -H "Accept: application/vnd.github.v3+json" \
+          "https://api.github.com/repos/${{ github.repository }}/dependabot/alerts")
         
         if echo "$response" | jq -e 'has("message")' > /dev/null; then
-          message=$(echo "$response" | jq -r '.message')
-          echo "::warning::API Response: $message"
+          echo "::warning::Error accessing Dependabot alerts: $(echo "$response" | jq -r '.message')"
           echo "[]" > dependabot_alerts.json
         else
           echo "$response" > dependabot_alerts.json
           
           if echo "$response" | jq -e 'length > 0' > /dev/null; then
-            echo "::warning::Found vulnerability alerts"
+            echo "::error::Found Dependabot security alerts"
             echo "SCAN_FAILED=true" >> $GITHUB_ENV
+            exit 1
           fi
         fi
     - name: Analyze dependencies
