remove DRY and add comments to jobs/steps

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -171,6 +171,21 @@ jobs:
         name: semgrep-results
         path: .
 
+    # Verify DefectDojo API token
+    - name: Verify DefectDojo API token
+      run: |
+        echo "Verifying DefectDojo API token..."
+        response=$(curl -X GET "$DEFECTDOJO_URL/api/v2/users/" \
+        -H "Authorization: Token $DEFECTDOJO_API_KEY" -w "\n%{http_code}")
+        http_code=$(echo "$response" | tail -n1)
+        body=$(echo "$response" | sed '$d')
+        echo "HTTP Status Code: $http_code"
+        echo "Response Body: $body"
+        if [ "$http_code" -ne 200 ]; then
+          echo "Invalid DefectDojo API token"
+          exit 1
+        fi
+
     # Upload Gitleaks results to DefectDojo
     - name: Upload Gitleaks results to DefectDojo
       run: |
